name: cli

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Run cli
        run: sudo chmod +x file.sh
        run: file.sh file.txt
